### ISSUE TITLE
Unable to synchronize WebGL-enabled canvas to Sampler2d

### ISSUE THREAD

**Issue by Qqwy** [gre/deprecated-glsl.js#15]
I have recently started using glsl.js, and I am very happy about this great tool. Most of my game is created using the PIXI.js framework, but to handle the shaders elegantly, I decided to use glsl.js .

However, PIXI.js renders all objects to a canvas using WebGL. When I then try to pass this canvas to the shader to be put in a Sampler2d object, it does not seem to work.
To be exact, it seems to work for one frame, that is I see it 'flicker' once and then the texture isn't shown anymore.

When I use the native canvas renderer of PIXI.js, it works fine, albeit far slower of course.

You can check my current test code with all canvases visible here: http://wmmusic.nl/codexamples/pixijs/glslwebgltest/smuv2.html

and how it looks with the canvas renderer:http://wmmusic.nl/codexamples/pixijs/v14/smuv2.html

**Comment by gre** [comment]
My guess: in glsl.js, `.start()` starts it's own update/render loop on the canvas you give, and maybe it should better follow a pixi's `render()`.
Maybe you can try to not use the `start()` and call the glsl.js' `render()` yourself after the Pixi `render`. (you may also need to call the glsl.js `update()` before these renders, with the right parameters.

Both your example are black screen for me.
Have some Stats is not defined error.

**Comment by Qqwy** [comment]
You were indeed correct. The problem turned out to be that I called a requestAnimFrame() from within my own starting function, and a second one was made by glsl.js . Now it is fully functionable. The performance is still kind of low, but that's probably because of having two separate WebGL contexts with these big size canvases. I'll try to integrate them more, should be doable.

Hmm... it seems that error about the Stats was caused by a Cross-Site Request problem that only Chrome suffers from, in FireFox it worked fine. But I've now saved the FPS counter locally, so that shouldnt be a problem either anymore. If you want, you can check the updated version here: http://wmmusic.nl/codexamples/pixijs/current/smuv2.html

Thank you very much for your reply!
