### ISSUE TITLE
Texture examples don't work on some machine

### ISSUE THREAD

**Issue by gre** [gre/deprecated-glsl.js#2]
The mario_sprites example seems not to work for a lot of people, have to investigate this.

I hope it's a solvable issue and not something linked to the graphic card.

Mario example is here: http://greweb.fr/glsl.js/examples/mario_sprites/

If you experiment the issue too, please copy/paste the result of these tests:
http://www.browserleaks.com/webgl

Here is mine (macbookpro):

```
WebGL Context Info
Context Name    experimental-webgl
GL Version  WebGL 1.0 (OpenGL ES 2.0 Chromium)
Shading Language Version    WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor  WebKit
Renderer    WebKit WebGL
Vertex Shader
Max Vertex Attributes   16
Max Vertex Uniform Vectors  1024
Max Vertex Texture Image Units  16
Max Varying Vectors 31
Rasterizer
Aliased Line Width Range    [1, 10]
Aliased Point Size Range    [1, 63]
Fragment Shader
Max Fragment Uniform Vectors    1024
Max Texture Image Units 16
Framebuffer
RGBA Bits   [8, 8, 8, 8]
Depth / Stencil Bits:   [24, 8]
Max Render Buffer Size  16384
Max Viewport Dimensions [16384, 16384]
Textures
Max Texture Size    16384
Max Cube Map Texture Size   16384
Max Combined Texture Image Units    16
Supported WebGL Extensions
OES_texture_float
OES_standard_derivatives
WEBKIT_EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBKIT_WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_depth_texture
```

**Comment by metastew** [comment]
I'm also experiencing this error too.

WebGL Context Info
Context Name    experimental-webgl
GL Version  WebGL 1.0
Shading Language Version    WebGL GLSL ES 1.0
Vendor  Mozilla
Renderer    Mozilla
Vertex Shader
Max Vertex Attributes   16
Max Vertex Uniform Vectors  254
Max Vertex Texture Image Units  4
Max Varying Vectors 10
Rasterizer
Aliased Line Width Range    [1, 1]
Aliased Point Size Range    [1, 256]
Fragment Shader
Max Fragment Uniform Vectors    221
Max Texture Image Units 16
Framebuffer
RGBA Bits   [8, 8, 8, 8]
Depth / Stencil Bits:   [24, 8]
Max Render Buffer Size  16384
Max Viewport Dimensions [16384, 16384]
Textures
Max Texture Size    16384
Max Cube Map Texture Size   16384
Max Combined Texture Image Units    20
Supported WebGL Extensions
OES_texture_float
OES_standard_derivatives
EXT_texture_filter_anisotropic
MOZ_WEBGL_lose_context
MOZ_WEBGL_compressed_texture_s3tc

In firefox, I found this error message relating to textures: 

```
Timestamp: 18/02/2013 3:25:07 PM
Warning: Error: WebGL: linkProgram failed, with this log:
(52,30): error X3090: ps_3_0 does not allow textures or samplers to be members of compound types
Source File: http://greweb.fr/glsl.js/glsl.js
Line: 479
```

**Comment by aostrega** [comment]
```
WebGL Context Info
Context Name    experimental-webgl
GL Version  WebGL 1.0 (OpenGL ES 2.0 Chromium)
Shading Language Version    WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor  WebKit
Renderer    WebKit WebGL
Vertex Shader
Max Vertex Attributes   16
Max Vertex Uniform Vectors  4096
Max Vertex Texture Image Units  16
Max Varying Vectors 16
Rasterizer
Aliased Line Width Range    [1, 5]
Aliased Point Size Range    [1, 255]
Fragment Shader
Max Fragment Uniform Vectors    4096
Max Texture Image Units 16
Framebuffer
RGBA Bits   [8, 8, 8, 8]
Depth / Stencil Bits:   [24, 8]
Max Render Buffer Size  8192
Max Viewport Dimensions [8192, 8192]
Textures
Max Texture Size    8192
Max Cube Map Texture Size   2048
Max Combined Texture Image Units    32
Supported WebGL Extensions
OES_texture_float
OES_standard_derivatives
WEBKIT_EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBKIT_WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_depth_texture
```

I have an integrated Intel GPU.

**Comment by gre** [comment]
"(52,30): error X3090: ps_3_0 does not allow textures or samplers to be members of compound types"

ok so it makes sense now, sampler2D as part of a struct seems to break.

Can you tell me if it works now?

**Comment by aostrega** [comment]
Works now :+1:

**Comment by gre** [comment]
Super! thanks for your help guys!
