### ISSUE TITLE
Vertex Shaders

### ISSUE THREAD

**Issue by johnpmayer** [gre/deprecated-glsl.js#8]
This seemed to be only briefly mentioned in your blog post.  I could see the benefit of having this same Uniform/Attribute access layer being able to support Model Matrix, Camera, Perspective for 3d models through vertex shaders. Could you expound upon the reason to only use fragment shaders?

**Comment by gre** [comment]
See my comment here: http://blog.greweb.fr/2013/02/glsl-js-a-javascript-glsl-library-dry-efficient/#comment-805868626

glsl.js is today more focus on accessing the fragment shader for 2D & filter/after-effect purpose than a complete 3D WebGL library.

From the start it is a subset of WebGL possibilities, like glsl.heroku.com is (but see how far some glsl.heroku.com examples go with just one frag shader!). I wanted to keep it as simple and stupid as possible, so it is also a start for learning GLSL.

You may look to another library (like Three.js) if it doesn't match your need.
If you find a use case of this, don't hesitate to fork it :-) so the library can evolve.

Regards,
gre
